SUBROUTINE TRIDIAG(MAT,TRIDIAGMAT,ROTMAT)
    USE DIAGMATMOD
    ! --- FOR ANY REPORT OR SUGGESTION, PLEASE CONTACT quentin.marecat@etu.umontpellier.fr --- !
    ! ---------------------------------------------------------------------------- !
    ! --- THIS SUBROUTINE TRIDIAGONALIZE THE SYMETRIC MATRIX MATRIX AND RETURN --- !
    ! --- THE TRIDIAGONALIZED MATRIX TRIDIAGMAT AND THE ROTATION MATRIX ROTMAT --- !
    ! ---------------------------------------------------------------------------- !
    IMPLICIT NONE 
    REAL*8,INTENT(IN) :: MAT(DIM,DIM)
    REAL*8,INTENT(OUT) :: TRIDIAGMAT(DIM,DIM), ROTMAT(DIM,DIM)
    REAL*8 :: ROTMATT(DIM,DIM), TRIANGSUP(DIM,DIM), ID(DIM,DIM)
    REAL*8 :: VEC(DIM), ROTMATTAMP(DIM,DIM)
    REAL*8 :: ROTMATTAMPT(DIM,DIM),MATTAMP(DIM,DIM)
    INTEGER :: LOWESTELEM
    TRIDIAGMAT = MAT
    ID = 0.
    DO I = 1,DIM
        ID(I,I) = 1.
    ENDDO
    ROTMAT = ID
    ROTMATT = ID
    DO LOWESTELEM = 1,DIM-2
        DO J = 1,DIM
            VEC(J) = TRIDIAGMAT(J,LOWESTELEM)
        ENDDO 
        CALL HOUSESTEP(VEC,LOWESTELEM+1,ROTMATTAMP)
        CALL PRODMAT(DIM,ROTMATTAMP,TRIDIAGMAT,TRIDIAGMAT)
        CALL TRANSPOSE(DIM,ROTMATTAMP, ROTMATTAMPT)
        CALL PRODMAT(DIM,TRIDIAGMAT,ROTMATTAMPT,TRIDIAGMAT)
                    ! --- VERIFICATION --- !
        TESTLOG = .FALSE.
        DO I = LOWESTELEM+2,DIM
            IF (ABS(TRIDIAGMAT(I,LOWESTELEM)) > EPS0 .OR. ABS(TRIDIAGMAT(LOWESTELEM,I)) > EPS0 &
            & .AND. ABS(TRIDIAGMAT(LOWESTELEM,LOWESTELEM+1)-TRIDIAGMAT(LOWESTELEM+1,LOWESTELEM)) < EPS0) TESTLOG = .TRUE.
        ENDDO
        IF (TESTLOG) THEN
            OPEN(UNIT = ERR, FILE = 'error')
            WRITE(6,'(A,I2)') 'PROBLEM HOUSESTEP'
            WRITE(ERR,'(A)')  'PROBLEM HOUSESTEP'
        ENDIF
        CALL PRODMAT(DIM,ROTMAT,ROTMATTAMP,ROTMAT)
        CALL PRODMAT(DIM,ROTMATTAMPT,ROTMATT,ROTMATT)
    ENDDO
    ! --- VERIFICATION --- !
    TESTLOG = .FALSE.
    DO I = 1,DIM-2
        DO J = I+2,DIM
            IF (ABS(TRIDIAGMAT(I,J)) > EPS0 .OR. ABS(TRIDIAGMAT(J,I)) > EPS0 &
            & .AND. ABS(TRIDIAGMAT(I,I+1)-TRIDIAGMAT(I+1,I)) < EPS0) TESTLOG = .TRUE.
        ENDDO
    ENDDO
    CALL PRODMAT(DIM,ROTMAT,TRIDIAGMAT,MATTAMP)
    CALL PRODMAT(DIM,MATTAMP,ROTMATT,MATTAMP)
    DO I = 1,DIM
        DO J = 1,DIM
            IF(ABS(MATTAMP(I,J)-MAT(I,J)) > EPS0) TESTLOG = .TRUE.
        ENDDO
    ENDDO
    IF (TESTLOG) THEN
        OPEN(UNIT = ERR, FILE = 'error')
        WRITE(ERR,'(A)')  'PROBLEM TRIDIAGONALISATION'
    ENDIF
END SUBROUTINE